### PR TITLE
Fixed minor issues for cleaner code

### PR DESCRIPTION
**Pull request by nikooo777**
Hey,
I am finally going slowly through some code. As first step i wanted to make sure the project is following the very basic standards so I fixed all the semicolons.
Can you please merge this change?

I will try to create as many pull requests as i can so you can choose what to merge and what not to merge.

Also, can you add me on steam? i sent you a pm on AM regarding that.

Greetings,
Niko

### CODE REVIEW

**Comment by nikooo777** [comment]
i ended up also fixing a bug with chat logging and converting the whole misc.sp to the new syntax.
I hope you like it :)

**Comment by nikooo777** [comment]
i'm keeping it synchronized. When you feel you want to merge the non disruptive changes you can just click on merge without efforts.

**Comment by nikooo777** [comment]
I know you don't consider converting to new syntax a priority at all, that's why i'm doing it for you.
I hope my hours of CTRL+F and replacing (boring non-programmer work) won't go to waste.

Meanwhile i took the chance to convert a couple other includes and fix some issues here and there. 
I run this version that i compiled on my servers and so far everything seems fine (but in the end i didn't really change anything crazy).

Don't hate me too much for doing this ;)

Greetings,
Niko

**Comment by jonitaikaponi** [comment]
Merged. Thanks a lot, cleaning the code is really going to help on the long run :).

**Pull request merged**
