### PR TITLE
UberPatch

### PR DESCRIPTION
**Pull request by nikooo777**
Hi Jonitaikaponi,
I have gone through the code with more attention now and I tried to sort out a little bit the mess.

If i have to be honest, i would start from scratch if i were you. However before doing that it's good to correct and practice over this huge plugin in order to get the skills necessary to code a clean plugin.

I am quite new at coding in sourcepawn myself however I try to follow the mechanisms i learned in university for programming, so please don't take everything I say for granted.

That said, this merge request is about 4 hours of my time going through the code and trying to understand what was written there and recoding it in a simpler way.

I managed to fix a lot of stuff and patch some mistakes.
I cleaned up unnecessary code and removed the spam filter as it's already provided by sourcemod:
https://wiki.alliedmods.net/Base_Plugins_(SourceMod) (antiflood.smx)

I also converted a couple stuff from old syntax to new syntax.

I enforced semicolons and fixed missing ones.

I changed the IsValidClient function to return false in case of fakeclients, I later realized that you were using that function when bots should actually pass that check, therefore i added a IsValidBot function and went through all the code to check those cases. I AM NOT SURE that i got them all, so you're encouraged to check yourself for those missing cases, however this is really good practice as you never forget to check for fakeclients which may cause a lot of issues if not handled.

I highly suggest you to comment every line of code you write from now on, because when you write them, they're very obvious to yourself, however after 1 week, not only everyone else, but also you will have no clue what was the thing you wrote.

If you want to enforce the new syntax i suggest you to set this in ckSurf.sp:
```
#pragma newdecls required
```

however it might take you a lot of time to convert everything.

Please take your time to read my changes, understand them, and eventually accept them.
I didn't test the plugin but it compiles without warnings.

Kiitos paljon for your consideration
Greetings,
Niko

PS: i added SM includes too because I like to work and compile in the project without relying on resources outside, feel free to ignore them

### CODE REVIEW

**Comment by jonitaikaponi** [comment]
Hey,

1. The spam filter of SM won't work, because ckSurf uses PrintToChatAll as
the chatting mechanism.
2. Moving more to the new syntax is ofcourse on the way, but takes a lot of
time to convert everything,
without much of an impact on the plugin itself.
3. There already is a IsFakeClient method in the plugin to check for bots
vs clients.
4. Commenting stuff should ofcourse be done, but as this plugin comes from
KZTimer, and KZTimers code wasn't commented, I haven't spent time going
throuch abckriegers code and commenting it. Most of my code is commented
usually.
5. Not going to enforce new syntax yet.


I noticed that most of the changes you made are on the if-statements,
removing comment blocks or adding semicolons, which doesn't really seem to
improve the plugin, so I probably won't be merging, as the code isn't
tested.

2015-12-02 5:21 GMT+02:00 Niko <notifications@github.com>:

**Comment by nikooo777** [comment]
Hi,
1) this is exactly the problem, it's not the correct way of doing it, Nothing else but your plugin will receive the chat. Nothing is logged to the game, nothing is logged to the console, you can't see the chat on HLSW nor hlstats. You really need to change how chat is handled.
A very good solution is to use already existing solutions:
https://forums.alliedmods.net/showthread.php?t=198501
for this reason: https://forums.alliedmods.net/showpost.php?p=1987954&postcount=8

1.5) if an admin decides to change the triggers to '-' or anything else, which is totally legit looking at sourcemod itself, then your plugin will deviate from the standard, for this reason you should consider not looking at the say hook but at regconsolecmd instead which will handle everything on its own

2) true, in the patch i converted quite some stuff to new syntax so that you can understand and get ideas from it
3) IsValidClient shouldn't return true if the checked client is a bot, also manually checking for fakeclient every time you don't need a bot to pass the check is just asking for troubles, in fact, most of the times you forgot to add that check. this is why you should use the one i provided.

4) :)

5) that's okay, but try to follow the new syntax when writing new code


Most of the changes are not in if-statements, that's just a minor part, please take a look at how i changed target acquisition, how i changed menu creation and other stuff. You can find out that the changes i did to these part of code can also be applied to many other parts of the code.

I'm not exactly asking you to blindly merge this, I'd like you to go over each change i did and decide whether it's a good idea to accept it and then implement it in your code.


Greetings,
Niko

**Comment by jonitaikaponi** [comment]
1. I know what the problem is, but a solution like SCP's is a long ways
away. The current solution is to disable ckSurf's chat processing with
ck_chat_enable 0. Also this isn't a really high priority, as you are pretty
much the only one who has requested this.

2. I know how the new syntax works, but it just isn't worth changing new
old big plugins into the new syntax, other than just making it compile. All
the new code that I've been making since the 1.18 patch, has been in the
new syntax.

3. Why should IsValidClient always return false on a bot?

5. Like I said, all the new code is in the new syntax. Won't be converting
the old code to the new more than it has been in 1.18b, as it just isn't
worth it.

2015-12-02 13:39 GMT+02:00 Niko <notifications@github.com>:

**Comment by nikooo777** [comment]
This is very outdated so i'll close it.
If i have time in the following weeks i'll try to perform the changes in the current version in a better way.

**Pull request closed without merging**
